### ISSUE TITLE
how to instantiate a controller class with injection in play framework 2.5.x

### ISSUE THREAD

**Issue by mullex** [playframework/play-mailer#125]
I just upgraded the play framework to 2.5.x. I refactored the mail sending function with play mail 5.0.0. However, When i try to send the email, i get error that the parameter doesn't match the signature.

How can i instantiate the MailHandler class without having to define a route?

```scala
class MailHandler @Inject()(mailer: MailerClient, val messagesApi: MessagesApi, environment: Environment) extends Controller with I18nSupport{
  def sendEmail(...) = {
    mailer.send(...)
  }
}
```
```
controllers.mail.MailHandler m = new controllers.mail.MailHandler();
m.sendAuthenticationSubmitEmail(user.email, type);
```

**Comment by marcospereira** [comment]
Hey @mullex, 

It is not about defining a route or not (although it is "unusual" to have controllers without defining the routes).

The problem here is that `MailerHandler` declares a controller that requires `MailerClient`, `MessagesApi` and `Environment` and your test is not passing these parameters when instantiating the `MailHandler`:

```java
controllers.mail.MailHandler m = new controllers.mail.MailHandler();
```

This needs to be something like:

```java
MailerClient mailer = ...
MessagesApi messagesApi = ...
Environment env = ...

controllers.mail.MailHandler m = new controllers.mail.MailHandler(mailer, messagesApi, env);
```
You decide if the instances will be mocked or not, but they need to be provided given the way you defined `MailerHandler`.

Finally, the [mailing list](https://groups.google.com/forum/#!forum/play-framework) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play and modules, not for general discussion and getting help.

Best.
