### ISSUE TITLE
No logs in mock mode (play 2.7)

### ISSUE THREAD

**Issue by EtienneLav** [playframework/play-mailer#164]
Do you know if mockmailer has been updated for play 2.7 ?

My mail is sent when i turn "mock" to "no" but nothing was logged when i set "mock = yes". 

Thanks

(  Version :
  "com.typesafe.play" %% "play-mailer" % "7.0.0",
  "com.typesafe.play" %% "play-mailer-guice" % "7.0.0"
)

**Comment by marcospereira** [comment]
Hey @EtienneLav, 

Our [forums](https://discuss.playframework.com) would be a better place to discuss this. Github issues are for reporting bugs and feature requests, not for general discussion and getting help. Given that, I'm closing this.

When using our forums, it would be good to share your logback.xml configuration as well, since the logs may not be appearing due to how the logging framework is configured.

Best.
